package org.cog.hymnchtv.reading.background

import com.google.common.truth.Truth.assertThat
import com.google.common.truth.Truth.assertWithMessage
import org.junit.Test
import java.io.File

/** Fails when res/ and BackgroundPreset drift apart or tools/gen_backgrounds.py was not re-run (plan A2). */
class BackgroundResourcesTest {
    private val res = File(checkNotNull(System.getProperty("hymnchtv.resDir")) { "hymnchtv.resDir not set" })
    private val drawableDirs: List<File> = res.listFiles { f -> f.isDirectory && f.name.startsWith("drawable") }!!.toList()
    private fun layer(p: BackgroundPreset) = File(res, "drawable/bg_${p.id}.xml")

    @Test
    fun everyPresetHasAGeneratedLayerList() {
        for (p in BackgroundPreset.entries) {
            assertWithMessage(p.id).that(layer(p).isFile).isTrue()
            assertWithMessage(p.id).that(layer(p).readText()).contains("Generated by tools/gen_backgrounds.py")
        }
    }

    @Test
    fun noLayerListWithoutAPreset() {
        val files = File(res, "drawable").listFiles { f -> f.name.matches(Regex("bg_[a-z]+\\.xml")) }!!.map { it.name }.toSet()
        assertThat(files).isEqualTo(BackgroundPreset.entries.map { "bg_${it.id}.xml" }.toSet())
    }

    @Test
    fun layerListsDeclareTheRegistryStops() {
        for (p in BackgroundPreset.entries) {
            val xml = layer(p).readText().lowercase()
            p.stops.forEach { s ->
                val hex = "#%06x".format(s and 0xFFFFFF)
                assertWithMessage("${p.id} should contain $hex").that(xml).contains(hex)
            }
        }
    }

    @Test
    fun referencedDrawablesExist() {
        val names = drawableDirs.flatMap { d -> d.listFiles()!!.map { it.name.substringBefore('.') } }.toSet()
        for (p in BackgroundPreset.entries) {
            Regex("@drawable/([a-z0-9_]+)").findAll(layer(p).readText()).forEach {
                assertWithMessage("${p.id} -> ${it.value}").that(names).contains(it.groupValues[1])
            }
        }
    }

    @Test
    fun generatedFilesStaySmall() {
        // bg_image.png is a pre-existing artwork, not generated: only bg_*.xml and bgx_* are checked
        val files = drawableDirs.flatMap { d -> d.listFiles { f -> (f.name.startsWith("bg_") && f.name.endsWith(".xml")) || f.name.startsWith("bgx_") }!!.toList() }
        assertThat(files).isNotEmpty()
        files.forEach { assertWithMessage(it.path).that(it.length()).isAtMost(5120L) }
    }
}
