package org.cog.hymnchtv.search

/**
 * Traditional -> Simplified candidates generated by tools/gen_lyrics_hant.py (assets/lyrics_t2s_map.txt).
 * Keys are single code points; a value lists every Simplified form seen for that key.
 * Coverage is limited to the forms OpenCC produced for the lyrics corpus.
 */
class T2sMap private constructor(private val map: Map<String, String>) {
    val size: Int get() = map.size

    /** @return the Simplified candidates for one code point string, or null if it needs no conversion. */
    fun candidates(codePoint: String): String? = map[codePoint]

    companion object {
        const val ASSET_PATH = "lyrics_t2s_map.txt"

        @JvmField
        val EMPTY = T2sMap(emptyMap())

        /** Lenient: malformed lines are skipped so a bad entry can never break search. */
        @JvmStatic
        fun parse(lines: Iterable<String>): T2sMap = T2sMap(
            lines.mapNotNull { line ->
                val cols = line.split('\t')
                val key = cols.getOrNull(0).orEmpty()
                val value = cols.getOrNull(1).orEmpty()
                if (cols.size == 2 && key.codePointCount(0, key.length) == 1 && value.isNotEmpty()) key to value else null
            }.toMap()
        )
    }
}
