package org.cog.hymnchtv.about

import org.json.JSONException
import org.json.JSONObject

data class LicenseInfo(val key: String, val name: String, val url: String?, val content: String?)

data class LicenseRow(
    val id: String,
    val name: String,
    val version: String?,
    val description: String?,
    val licenses: List<LicenseInfo>,
)

/** Reads the aboutlibraries.json generated by the AboutLibraries Gradle plugin (R.raw.aboutlibraries). */
object AboutLibrariesJson {
    /** Project notices shown first, in this order; the font entry is added by sub-project A2. */
    val PINNED = listOf("org.cog:hymnchtv", "org.byvoid:opencc-data", "org.cog.hymnal:hymnalkai-font")

    @JvmStatic
    fun parse(json: String?): List<LicenseRow> {
        if (json.isNullOrBlank()) return emptyList()
        return try {
            val root = JSONObject(json)
            val licenses = root.optJSONObject("licenses") ?: JSONObject()
            val libraries = root.getJSONArray("libraries")
            (0 until libraries.length())
                .mapNotNull { libraries.optJSONObject(it)?.let { lib -> toRow(lib, licenses) } }
                .sortedWith(compareBy<LicenseRow> { pinIndex(it.id) }.thenBy { it.name.lowercase() })
        } catch (e: JSONException) {
            emptyList()
        }
    }

    private fun pinIndex(id: String): Int = PINNED.indexOf(id).let { if (it < 0) PINNED.size else it }

    private fun toRow(lib: JSONObject, licenses: JSONObject): LicenseRow? {
        val id = lib.stringOrNull("uniqueId") ?: return null
        val keys = lib.optJSONArray("licenses")
        val infos = (0 until (keys?.length() ?: 0)).mapNotNull { keys?.optString(it)?.takeIf { k -> k.isNotEmpty() } }
            .map { key -> toLicense(key, licenses.optJSONObject(key)) }
        return LicenseRow(id, lib.stringOrNull("name") ?: id, lib.stringOrNull("artifactVersion"), lib.stringOrNull("description"), infos)
    }

    private fun toLicense(key: String, obj: JSONObject?): LicenseInfo =
        LicenseInfo(key, obj?.stringOrNull("name") ?: key, obj?.stringOrNull("url"), obj?.stringOrNull("content"))

    private fun JSONObject.stringOrNull(key: String): String? =
        if (!has(key) || isNull(key)) null else optString(key).takeIf { it.isNotBlank() }
}
