package org.cog.hymnchtv.about

import android.app.AlertDialog
import android.os.Bundle
import android.widget.ArrayAdapter
import android.widget.ListView
import android.widget.ScrollView
import android.widget.TextView
import org.cog.hymnchtv.BaseActivity
import org.cog.hymnchtv.HymnsApp
import org.cog.hymnchtv.R
import timber.log.Timber
import java.io.IOException

/** Native list of open-source licenses generated by the AboutLibraries Gradle plugin (R.raw.aboutlibraries). */
class LicensesActivity : BaseActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.licenses)
        setTitle(R.string.about_licenses_title)
        val list = findViewById<ListView>(R.id.licenses_list)
        list.emptyView = findViewById(R.id.licenses_empty)
        Thread({
            val rows = loadRows()
            runOnUiThread { if (!isFinishing) bind(list, rows) }
        }, "hymnal-licenses").start()
    }

    private fun bind(list: ListView, rows: List<LicenseRow>) {
        list.adapter = ArrayAdapter(this, android.R.layout.simple_list_item_1, rows.map(LicenseText::title))
        list.setOnItemClickListener { _, _, position, _ -> showDetail(rows[position]) }
    }

    /** Looked up by name so this screen still builds before the plugin is applied (Task 12). */
    private fun loadRows(): List<LicenseRow> {
        val resId = HymnsApp.getFileResId("aboutlibraries", "raw")
        if (resId == 0) return emptyList()
        return try {
            resources.openRawResource(resId).bufferedReader().use { AboutLibrariesJson.parse(it.readText()) }
        } catch (e: IOException) {
            Timber.w(e, "Cannot read license data")
            emptyList()
        }
    }

    private fun showDetail(row: LicenseRow) {
        val padding = (16 * resources.displayMetrics.density).toInt()
        val text = TextView(this).apply {
            text = LicenseText.detail(row, getString(R.string.about_license_text_missing))
            setTextIsSelectable(true)
            setPadding(padding, padding, padding, padding)
        }
        AlertDialog.Builder(this)
            .setTitle(row.name)
            .setView(ScrollView(this).apply { addView(text) })
            .setPositiveButton(R.string.ok, null)
            .show()
    }
}
