#!/usr/bin/env python3
"""Generate the reading-background drawables (plan A2): layer-lists, motif vectors, texture and tile PNGs.

Usage: tools/gen_backgrounds.py
Stdlib only and deterministic: running it twice produces identical files.
Colours mirror BackgroundPreset.kt; BackgroundResourcesTest checks that every declared stop appears here.
"""
import math
import pathlib
import random
import struct
import sys
import zlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
RES = ROOT / "hymnchtv/src/main/res"
DRAWABLE = RES / "drawable"
NODPI = RES / "drawable-nodpi"
XXHDPI = RES / "drawable-xxhdpi"
ANDROID_NS = 'xmlns:android="http://schemas.android.com/apk/res/android"'
HEADER = "<!-- Generated by tools/gen_backgrounds.py; do not edit by hand. -->"
MAX_BYTES = 5120
NOISE_SIZE = 96   # px, drawable-nodpi
NOISE_CELL = 12   # px per value-noise lattice cell; 96 / 12 = 8 cells, so the tile wraps seamlessly
LEVELS = 16       # 4-bit palette: 16 alpha steps of one colour


def alpha(a):
    return int(a * 255 + 0.5)


def argb(rgb_hex, a):
    return "#%02x%s" % (alpha(a), rgb_hex.lstrip("#"))


def num(v):
    text = ("%.2f" % v).rstrip("0").rstrip(".")
    return "0" if text in ("-0", "") else text


def png(path, width, height, rows, color_type, bit_depth=8, palette=None, trns=None):
    def chunk(tag, data):
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    raw = b"".join(b"\x00" + bytes(r) for r in rows)
    out = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, bit_depth, color_type, 0, 0, 0))
    if palette:
        out += chunk(b"PLTE", bytes(palette))
    if trns:
        out += chunk(b"tRNS", bytes(trns))
    out += chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")
    path.write_bytes(out)


# ---------- textures and tiles ----------

NOISE = {  # name: (grain colour, strongest alpha) -- CSS feTurbulence colour, alpha doubled for the peak
    "xuan": ("#594d40", 0.14),
    "parchment": ("#735226", 0.20),
    "nightread": ("#e6d9bf", 0.10),
    "ink": ("#ccccd9", 0.12),
}


def noise_tile(name, rgb_hex, max_alpha):
    rnd = random.Random("hymnal-" + name)
    cells = NOISE_SIZE // NOISE_CELL
    lattice = [[rnd.random() for _ in range(cells)] for _ in range(cells)]

    def smooth(x, y):
        gx, gy = x / NOISE_CELL, y / NOISE_CELL
        x0, y0 = int(gx), int(gy)
        fx, fy = gx - x0, gy - y0
        fx, fy = fx * fx * (3 - 2 * fx), fy * fy * (3 - 2 * fy)
        x1, y1 = (x0 + 1) % cells, (y0 + 1) % cells
        top = lattice[y0][x0] + (lattice[y0][x1] - lattice[y0][x0]) * fx
        bottom = lattice[y1][x0] + (lattice[y1][x1] - lattice[y1][x0]) * fx
        return top + (bottom - top) * fy

    rows = []
    for y in range(NOISE_SIZE):
        levels = [min(LEVELS - 1, int((0.5 * rnd.random() + 0.5 * smooth(x, y)) * LEVELS)) for x in range(NOISE_SIZE)]
        rows.append([(levels[i] << 4) | levels[i + 1] for i in range(0, NOISE_SIZE, 2)])
    r, g, b = bytes.fromhex(rgb_hex.lstrip("#"))
    top = alpha(max_alpha)
    trns = [round(i * top / (LEVELS - 1)) for i in range(LEVELS)]
    png(NODPI / f"bgx_tex_{name}.png", NOISE_SIZE, NOISE_SIZE, rows, color_type=3, bit_depth=4,
        palette=[r, g, b] * LEVELS, trns=trns)


def staff_tile():
    """240 x 64 dp at xxhdpi (3 px/dp); five 1 dp staff lines at y = 14, 20, 26, 32, 38 dp."""
    s, w, h = 3, 240 * 3, 64 * 3
    line = [70, 80, 100, alpha(0.13)] * w
    clear = [0, 0, 0, 0] * w
    ys = {y * s + k for y in (14, 20, 26, 32, 38) for k in range(s)}
    png(XXHDPI / "bgx_tile_staff.png", w, h, [line if y in ys else clear for y in range(h)], color_type=6)


def linen_tile():
    """3 dp grid of 1 dp black hairlines at 2.5 %; crossings stack like the two CSS gradients."""
    s = 3
    steps = (0, alpha(0.025), alpha(1 - (1 - 0.025) ** 2))
    rows = [sum(([0, 0, 0, steps[(y < s) + (x < s)]] for x in range(3 * s)), []) for y in range(3 * s)]
    png(XXHDPI / "bgx_tile_linen.png", 3 * s, 3 * s, rows, color_type=6)


# ---------- motif vectors ----------

def path(d, fill=None, stroke=None, width=None):
    attrs = [f'android:pathData="{d}"']
    if fill:
        attrs.append(f'android:fillColor="{fill}"')
    if stroke:
        attrs += [f'android:strokeColor="{stroke}"', f'android:strokeWidth="{num(width)}"']
    return "    <path\n" + "".join(f"        {a}\n" for a in attrs[:-1]) + f"        {attrs[-1]} />\n"


def circle_d(cx, cy, r):
    return f"M{num(cx - r)},{num(cy)} a{num(r)},{num(r)} 0 1,0 {num(2 * r)},0 a{num(r)},{num(r)} 0 1,0 {num(-2 * r)},0 Z"


def ellipse_d(cx, cy, rx, ry, rot):
    """Closed sub-path for an ellipse rotated by rot degrees (SVG arcs carry the rotation, so no <group> is needed)."""
    t = math.radians(rot)
    dx, dy = rx * math.cos(t), rx * math.sin(t)
    arc = f"a{num(rx)},{num(ry)} {num(rot)} 1,0"
    return f"M{num(cx - dx)},{num(cy - dy)} {arc} {num(2 * dx)},{num(2 * dy)} {arc} {num(-2 * dx)},{num(-2 * dy)} Z"


def vector(name, w, h, body):
    xml = (f'<?xml version="1.0" encoding="utf-8"?>\n{HEADER}\n<vector {ANDROID_NS}\n'
           f'    android:width="{w}dp"\n    android:height="{h}dp"\n'
           f'    android:viewportWidth="{w}"\n    android:viewportHeight="{h}">\n{body}</vector>\n')
    (DRAWABLE / f"bgx_motif_{name}.xml").write_text(xml, encoding="utf-8")


def olive():
    leaves = [(150, 24, -35), (132, 40, -50), (118, 30, 20), (110, 58, -55), (96, 50, 25),
              (92, 80, -60), (76, 74, 30), (72, 104, -65), (58, 98, 30), (54, 128, -70)]
    body = path("M170,10 C120,40 80,80 40,160", stroke=argb("#5c6e3c", 0.35), width=2)
    body += path(" ".join(ellipse_d(x, y, 13, 5, r) for x, y, r in leaves), fill=argb("#6e8246", 0.22))
    vector("olive", 170, 170, body)


def wheat():
    stems = ("M30,180 C34,120 40,80 52,30", "M70,180 C70,120 74,90 86,44", "M110,180 C106,130 108,100 118,60")
    body = "".join(path(d, stroke=argb("#967328", 0.35), width=1.6) for d in stems)
    grains = [ellipse_d(x + dx, y + dy + i * 11, 4, 7, rot)
              for x, y in ((52, 30), (86, 44), (118, 60)) for i in range(5) for dx, dy, rot in ((-4, 10, -25), (5, 14, 25))]
    body += path(" ".join(grains), fill=argb("#be963c", 0.25))
    vector("wheat", 150, 180, body)


def dove():
    body = path("M18,70 C40,60 58,58 74,62 C70,40 80,18 104,6 C98,26 100,40 108,52 C118,50 128,52 136,58 "
                "C124,60 116,66 112,74 C100,94 70,102 44,92 C34,88 24,84 4,86 C12,80 16,76 18,70 Z",
                fill=argb("#5a78a0", 0.16))
    body += path(circle_d(118, 57, 1.8), fill=argb("#3c506e", 0.35))
    vector("dove", 140, 110, body)


def vine():
    body = path("M0,30 C40,20 70,40 90,70 S130,120 170,130", stroke=argb("#645078", 0.3), width=2)
    grapes = ((70, 62), (64, 72), (76, 72), (70, 82), (60, 82), (80, 82), (66, 92), (74, 92), (70, 101))
    body += path(" ".join(circle_d(x, y, 5) for x, y in grapes), fill=argb("#6e508c", 0.2))
    body += path("M108,92 C120,76 140,80 138,98 C130,96 122,104 120,112 C110,106 104,100 108,92 Z",
                 fill=argb("#5a7846", 0.2))
    vector("vine", 170, 170, body)


def waves():
    """Two rows of the 120 x 40 CSS wave tile, laid out as on a 360 dp wide screen (row 2 shifted 30 dp)."""
    def row(x0, y):
        d, x = f"M{x0},{y} Q{x0 + 15},{y - 12} {x0 + 30},{y}", x0 + 30
        while x < 360:
            x += 30
            d += f" T{x},{y}"
        return d

    stroke = argb("#286e8c", 0.22)
    vector("waves", 360, 62, path(row(-120, 42), stroke=stroke, width=1.6) + path(row(-90, 20), stroke=stroke, width=1.6))


# ---------- layer-lists (one per preset) ----------

def color(c):
    return f'    <item>\n        <color android:color="{c}" />\n    </item>\n'


def gradient(start, end, center=None, center_y=None, radial=False):
    attrs = ['android:type="radial"' if radial else 'android:type="linear"']
    if not radial:
        attrs.append('android:angle="270"')
    attrs += [f'android:startColor="{start}"']
    if center:
        attrs.append(f'android:centerColor="{center}"')
    attrs.append(f'android:endColor="{end}"')
    if radial:
        attrs += ['android:centerX="0.5"', 'android:gradientRadius="115%p"']
    if center_y is not None:
        attrs.append(f'android:centerY="{num(center_y)}"')
    body = "".join(f"                {a}\n" for a in attrs[:-1]) + f"                {attrs[-1]} />\n"
    return f'    <item>\n        <shape android:shape="rectangle">\n            <gradient\n{body}        </shape>\n    </item>\n'


def tile(name):
    return f'    <item>\n        <bitmap\n            android:src="@drawable/{name}"\n            android:tileMode="repeat" />\n    </item>\n'


def motif(name, gravity, width, height, **insets):
    attrs = [f'android:drawable="@drawable/bgx_motif_{name}"', f'android:gravity="{gravity}"']
    if width:
        attrs.append(f'android:width="{width}dp"')
    attrs.append(f'android:height="{height}dp"')
    attrs += [f'android:{k}="{v}dp"' for k, v in insets.items()]
    return "    <item\n" + "".join(f"        {a}\n" for a in attrs[:-1]) + f"        {attrs[-1]} />\n"


LAYERS = {
    "xuan": [color("#f8f6f0"), tile("bgx_tex_xuan")],
    "linen": [color("#ecebe6"), tile("bgx_tile_linen")],
    "parchment": [gradient("#f6ead0", "#e3cd9e", center="#f6ead0", center_y=0.5, radial=True), tile("bgx_tex_parchment")],
    "mist": [color("#e7eef3")],
    "dawn": [gradient("#fbd9bd", "#fffaf4", center="#fff1e2", center_y=0.45)],
    "sky": [gradient("#c9def2", "#f8fbfe", center="#eef5fb", center_y=0.6)],
    "harvest": [gradient("#f3dd9b", "#fdf9ec", center="#faf0d2", center_y=0.55)],
    "dusk": [gradient("#e3d6ef", "#fcf3f6", center="#f6e4ec", center_y=0.6)],
    "meadow": [gradient("#f6fbf2", "#d5ead0", center="#e5f2df", center_y=0.7)],
    "staff": [color("#faf9f5"), tile("bgx_tile_staff")],
    "olive": [color("#f7f8f1"), motif("olive", "top|right", 150, 150, top=-6, right=-10)],
    "wheat": [gradient("#fffdf6", "#f8f0da"), motif("wheat", "bottom|right", 120, 144, bottom=-10, right=4)],
    "dove": [gradient("#eef3f9", "#fafcfe"), motif("dove", "top|right", 110, 86, top=34, right=10)],
    "rays": [gradient("#fbe7b9", "#fdf6e6", center="#fdf6e6", center_y=0.7)],  # rays drawn in code (RaysDrawable)
    "water": [gradient("#f5fbfc", "#e1f0f3"), motif("waves", "bottom|fill_horizontal", None, 62)],
    "vine": [color("#faf8fb"), motif("vine", "bottom|left", 150, 150, bottom=-10, left=-20)],
    "nightread": [color("#24211d"), tile("bgx_tex_nightread")],
    "starry": [gradient("#0f1a33", "#1c2a4a")],  # stars drawn in code (StarsDrawable)
    "deepsea": [gradient("#0f2a33", "#123d42")],
    "ink": [color("#1b1d22"), tile("bgx_tex_ink")],
}


def layer_list(name, items):
    xml = f'<?xml version="1.0" encoding="utf-8"?>\n{HEADER}\n<layer-list {ANDROID_NS}>\n' + "".join(items) + "</layer-list>\n"
    (DRAWABLE / f"bg_{name}.xml").write_text(xml, encoding="utf-8")


def clean():
    for folder in (DRAWABLE, NODPI, XXHDPI):
        folder.mkdir(parents=True, exist_ok=True)
        for f in list(folder.glob("bg_*.xml")) + list(folder.glob("bgx_*")):
            f.unlink()


def main():
    clean()
    for name, (rgb, a) in NOISE.items():
        noise_tile(name, rgb, a)
    staff_tile()
    linen_tile()
    for make in (olive, wheat, dove, vine, waves):
        make()
    for name, items in LAYERS.items():
        layer_list(name, items)
    outputs = sorted(p for d in (DRAWABLE, NODPI, XXHDPI) for p in list(d.glob("bg_*.xml")) + list(d.glob("bgx_*")))
    too_big = [p for p in outputs if p.stat().st_size > MAX_BYTES]
    for p in outputs:
        print(f"{p.stat().st_size:6d}  {p.relative_to(ROOT)}")
    if too_big:
        sys.exit(f"over {MAX_BYTES} bytes: {', '.join(p.name for p in too_big)}")
    print(f"Generated {len(outputs)} files ({len(LAYERS)} backgrounds)")


if __name__ == "__main__":
    main()
