#!/usr/bin/env python3
"""Derive Recovery Version character preferences (tools/rcv_word_prefs.tsv, tools/rcv_char_prefs.tsv).

Usage: tools/gen_rcv_prefs.py CORPUS.txt [--secondary FILE ...]
CORPUS.txt is the Recovery Version text from recoveryversion.com.tw (plain UTF-8, one verse per line): the
authority for glyphs and word choice. Secondary files (plain text, or .jsonl with a "text" field per record; e.g.
the Recovery Version footnotes and ministry books) only veto primary context rows they contradict. All corpora are
copyrighted and must never be committed; only the derived counts are. See tools/rcv_prefs.py for the model and
thresholds. Requires the OpenCC CLI; output is deterministic for the same corpus and OpenCC version.
"""
import argparse
import hashlib
import json
import os
import pathlib
import shutil
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import rcv_prefs as rp  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
WORD_TABLE = ROOT / "tools/rcv_word_prefs.tsv"
CHAR_TABLE = ROOT / "tools/rcv_char_prefs.tsv"


def opencc(text, config):
    try:
        result = subprocess.run(["opencc", "-c", config], input=text.encode("utf-8"), capture_output=True, check=True)
    except subprocess.CalledProcessError as e:
        sys.exit(f"opencc -c {config} failed: {e.stderr.decode(errors='replace')}")
    return result.stdout.decode("utf-8")


def aligned_lines(corpus_text):
    """(sim, tw, rcv) per line; lines whose length OpenCC changed are dropped (no reliable alignment)."""
    rcv = corpus_text.splitlines()
    sim = opencc(corpus_text, "t2s.json").splitlines()
    tw = opencc("\n".join(sim) + "\n", "s2tw.json").splitlines()
    if not (len(rcv) == len(sim) == len(tw)):
        sys.exit("OpenCC changed the line count of the corpus")
    kept = [(s, t, r) for s, t, r in zip(sim, tw, rcv) if len(s) == len(t) == len(r)]
    return kept, len(rcv) - len(kept)


def read_corpus(path):
    data = path.read_bytes()
    if path.suffix != ".jsonl":
        return data, data.decode("utf-8")
    texts = [json.loads(line).get("text") or "" for line in data.decode("utf-8").splitlines() if line.strip()]
    return data, "\n".join(texts)


def secondary_lines(text):
    """(sim, sim, text) lines for a secondary corpus; length-changed lines are dropped."""
    lines = text.splitlines()
    sim = opencc("\n".join(lines) + "\n", "t2s.json").splitlines()
    if len(sim) != len(lines):
        sys.exit("OpenCC changed the line count of a secondary corpus")
    return [(s, s, t) for s, t in zip(sim, lines) if len(s) == len(t)]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("corpus", type=pathlib.Path, help="Recovery Version plain text (not in the repo)")
    parser.add_argument("--secondary", type=pathlib.Path, nargs="*", default=[], help="weaker corpora (veto only)")
    args = parser.parse_args()
    if shutil.which("opencc") is None:
        sys.exit("opencc not found: brew install opencc")
    data = args.corpus.read_bytes()
    aligned, dropped = aligned_lines(data.decode("utf-8"))
    if not aligned:
        sys.exit("empty corpus")
    contested = sorted(rp.contested_chars(aligned))
    defaults = dict(zip(contested, opencc("\n".join(contested) + "\n", "s2tw.json").splitlines()))
    secondary, sources = [], []
    for path in args.secondary:
        raw, text = read_corpus(path)
        lines = secondary_lines(text)
        secondary += lines
        sources.append(f"{path.name} sha1 {hashlib.sha1(raw).hexdigest()} ({len(lines)} lines)")
    prefs = rp.build_prefs(aligned, defaults, secondary)
    _, _, _, _, per_a = rp.collect(aligned, set(prefs.uni))

    header = [
        "# generated by tools/gen_rcv_prefs.py from the Recovery Version text (recoveryversion.com.tw)",
        f"# corpus sha1 {hashlib.sha1(data).hexdigest()}, {len(aligned)} aligned lines ({dropped} dropped), "
        f"{sum(len(r) for _, _, r in aligned)} chars",
        f"# secondary (veto only): {'; '.join(sources) or 'none'}",
        f"# thresholds: contested >= {rp.CONTEST_MIN} disagreements; context >= {rp.CTX_MIN} occurrences and "
        f">= {rp.CTX_SHARE:.0%}; char rule >= {rp.CHAR_MIN}, >= {rp.CHAR_SHARE:.0%} and >= {rp.CHAR_CONTEXTS} contexts; bigrams stored >= {rp.BIGRAM_STORE_MIN}",
    ]
    tables = {WORD_TABLE: [rp.WORD_HEADER] + rp.format_word_table(prefs),
              CHAR_TABLE: [rp.CHAR_HEADER] + rp.format_char_table(prefs, per_a)}
    for path, rows in tables.items():  # write both, then swap both in
        path.with_suffix(".tmp").write_text("\n".join(header + rows) + "\n", encoding="utf-8")
    for path in tables:
        os.replace(path.with_suffix(".tmp"), path)
    print(f"{len(prefs.uni)} contested chars, {len(prefs.char)} char rules, "
          f"{len(prefs.left) + len(prefs.right)} bigram rows, {len(prefs.tri)} trigram rows")


if __name__ == "__main__":
    main()
